# version: '3.8'

# services:
#   mongodb:
#     image: mongo:4.4
#     container_name: ecommerce_mongodb
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:


version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: ecommerce_mongodb_second
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongodb_consumer:
    image: mongo:4.4
    container_name: ecommerce_mongodb_consumer
    volumes:
      - mongodb_data:/data/db
    command: ["tail", "-f", "/dev/null"]

volumes:
  mongodb_data: